"""add archived status and consecutive errors

Revision ID: 04a867e02dc9
Revises: 2ee831006722
Create Date: 2026-07-14 10:24:09.634510

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04a867e02dc9"
down_revision: str | Sequence[str] | None = "2ee831006722"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'archived'")
    op.add_column(
        "subscriptions",
        sa.Column(
            "consecutive_errors",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Счетчик последовательных ошибок парсинга",
        ),
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "price_rise_alert_sent",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Было ли отправлено уведомление о росте цены (Задача 4)",
        ),
    )
    op.create_index(
        "ix_subscriptions_active_status_last_check",
        "subscriptions",
        ["is_active", "status", "last_check_at"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_subscriptions_active_status_last_check", table_name="subscriptions"
    )
    op.drop_column("subscriptions", "price_rise_alert_sent")
    op.drop_column("subscriptions", "consecutive_errors")
    # ### end Alembic commands ###
