"""add_last_alert_at_and_cooldown_hours

Revision ID: 2ee831006722
Revises: d52f2823cf5f
Create Date: 2026-07-08 10:15:07.567929

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ee831006722"
down_revision: str | Sequence[str] | None = "d52f2823cf5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "last_alert_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время последнего отправленного уведомления",
        ),
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "cooldown_hours",
            sa.Integer(),
            nullable=False,
            server_default="24",
            comment="Период cooldown в часах между уведомлениями",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "cooldown_hours")
    op.drop_column("subscriptions", "last_alert_at")
    # ### end Alembic commands ###
