"""cleanup_subscription_model

Revision ID: be21a0b854c2
Revises: 146f5cbf6c6c
Create Date: 2026-07-03 10:52:34.239211

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be21a0b854c2"
down_revision: str | Sequence[str] | None = "146f5cbf6c6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "product_url",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.String(length=2000),
        existing_nullable=False,
    )
    op.alter_column(
        "subscriptions",
        "product_name",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
    op.drop_column("subscriptions", "last_task_id")
    op.execute("ALTER TABLE subscriptions ALTER COLUMN status DROP DEFAULT")
    op.execute("CREATE TYPE subscriptionstatus_new AS ENUM ('idle', 'failed')")
    op.execute(
        "ALTER TABLE subscriptions ALTER COLUMN status TYPE subscriptionstatus_new "
        "USING status::text::subscriptionstatus_new"
    )
    op.execute("DROP TYPE subscriptionstatus")
    op.execute("ALTER TYPE subscriptionstatus_new RENAME TO subscriptionstatus")
    op.execute(
        "ALTER TABLE subscriptions ALTER COLUMN status SET DEFAULT 'idle'::subscriptionstatus"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE subscriptions ALTER COLUMN status DROP DEFAULT")
    op.execute(
        "CREATE TYPE subscriptionstatus_old AS ENUM "
        "('idle', 'scheduled', 'running', 'completed', 'failed')"
    )
    op.execute(
        "ALTER TABLE subscriptions ALTER COLUMN status TYPE subscriptionstatus_old "
        "USING status::text::subscriptionstatus_old"
    )
    op.execute("DROP TYPE subscriptionstatus")
    op.execute("ALTER TYPE subscriptionstatus_old RENAME TO subscriptionstatus")
    op.execute(
        "ALTER TABLE subscriptions ALTER COLUMN status SET DEFAULT 'idle'::subscriptionstatus"
    )
    op.add_column(
        "subscriptions",
        sa.Column("last_task_id", sa.String(36), nullable=True),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "product_name",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=512),
        existing_nullable=True,
    )
    op.alter_column(
        "subscriptions",
        "product_url",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
